# Generated by Django 6.0 on 2025-12-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkplaceBooking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='booked_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='booked_date',
            field=models.DateField(null=True),
        ),
    ]
